// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSmCbG_5OXmEgW9RVOJK-pH-OlQK04cU8',
    appId: '1:848397038473:web:323f1b1a5ebd7fe426e758',
    messagingSenderId: '848397038473',
    projectId: 'offerzhub-10b97',
    authDomain: 'offerzhub-10b97.firebaseapp.com',
    storageBucket: 'offerzhub-10b97.firebasestorage.app',
    measurementId: 'G-Y45GKW4CJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWKpcLPYGUVuteyZFw9q3rYu3JM4M8TfA',
    appId: '1:848397038473:android:43e82bd572ae74cc26e758',
    messagingSenderId: '848397038473',
    projectId: 'offerzhub-10b97',
    storageBucket: 'offerzhub-10b97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnuNWUFnaqd0NO2bXT1jNHdgtC3sTKyeM',
    appId: '1:848397038473:ios:b54ea8649424802926e758',
    messagingSenderId: '848397038473',
    projectId: 'offerzhub-10b97',
    storageBucket: 'offerzhub-10b97.firebasestorage.app',
    iosClientId: '848397038473-1frn9uvsudnnedrbc8m64lljdtpouckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.offerzhub',
  );
}
